# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: some_db
    ports:
      - "5432:5432"
#    volumes:
#      - :/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure